chore: refactor, update themes and improve setup script
- .bashrc: ensure `.cargo/env` is sourced only if existing; set HISTSIZE and
  HISTFILESIZE to 500
- Added bat configuration with (uncomplete) gruvbox-material theme
- Added btop configuration
- Grouped Lazyvim common plugins into multiple single lua modules
- Fixed README typos
- Updated rofi UI and replaced gruvbox theme with gruvbox-material
- Added an fzf-preview.sh to cleanly handle `fzf --preview`, unlink the previous method which polluted `printenv`
- Replaced fzf color theme from gruvbox to gruvbox-material
- Improved dotfiles setup script:
  - Added colorful logging
  - Added path validation and helper functions
  - Extracted reusable logic into `setup/lib`

diff --git a/.local/bin/note b/.local/bin/note
--- a/.local/bin/note
+++ b/.local/bin/note
@@ -3,10 +3,11 @@
 # ┌─────────────────────────────┐
 # │ nvim + syncthing + obsidian │
 # └─────────────────────────────┘
+# Opens `~/Documents/Notes/` with `nvim` alongside with `obsidian` and `syncthing` for note-taking.
 
 # Start config
-SUBFOLDER_SELECT=0
-vault="$HOME"/Documents/Notes
+SUBFOLDER_SELECT=0            # Set to '1' to enable subfolder selector
+vault="$HOME"/Documents/Notes # Default vault
 # End config
 
 if [[ $# -eq 1 ]]; then
@@ -15,63 +16,62 @@ else
   target_directory="$vault"
 fi
 
-encoded_target_directory=$(printf "%s" "$target_directory" | sed "s/\//%2F/g; s/ /%20/g")
+encoded_target_directory=$(printf "%s\n" "$target_directory" | sed "s/\//%2F/g; s/ /%20/g")
 
 # Opens Obsidian if not already running
 if pgrep -fla "electron" | grep -q "obsidian://open?path=$encoded_target_directory"; then
-  echo "Obsidian is already running"
+  printf "Obsidian is already running\n"
 else
-  echo "Opening Obsidian on path: $target_directory..."
+  printf "Opening Obsidian on path: %s...\n" "$target_directory"
   nohup xdg-open "obsidian://open?path=$encoded_target_directory" >/dev/null 2>&1 &
   disown
 fi
 
 cd "$target_directory" || {
-  echo "Failed to change directory to $target_directory"
+  printf "Failed to change directory to %s\n" "$target_directory"
   exit 1
 }
 
 if ! pgrep -x "syncthing" >/dev/null; then
   # Initialize syncthing in the background
-  echo "Initializing syncthing..."
+  printf "Initializing syncthing...\n"
   syncthing -no-browser >/dev/null &
   disown
 
-  echo "[TIP] Please check if devices are on the same WIFI SSID to ensure syncing."
+  printf "[TIP] Please check if devices are on the same WIFI SSID to ensure syncing\n"
 
   # Add 10 seconds delay to allow Syncthing sync missing files
   for i in {10..1}; do
-    echo -ne "\rWaiting for sync: $i seconds remaning... "
+    printf "\rWaiting for sync: %d seconds remaning... " "$i"
     sleep 1
   done
-  echo -e "\nSyncthing initialization complete. Files are ready for editing."
+  printf "\nSyncthing initialization complete. Files are ready for editing.\n"
 
 else
-  echo "Syncthing is already running"
+  printf "Syncthing is already running\n"
 fi
 
 sleep 0.5
 
-if [ "$SUBFOLDER_SELECT" = 1 ]; then
+if [[ "$SUBFOLDER_SELECT" == 1 ]]; then
   # Select subfolder
   folders=$(find . -mindepth 1 -maxdepth 1 -type d \
     ! -name '.*' \
     ! -name 'Excalidraw' \
     ! -name 'Attachments' |
     sed 's|^\./||')
-  selected_folder=$(echo "$folders" | fzf --prompt="Please select: " --border --reverse)
-  selected_folder=$(echo "$selected_folder" | xargs)
+  selected_folder=$(printf "%s\n" "$folders" | fzf --prompt="Please select: " --border --reverse | xargs)
 
   # Navigate to the selected folder
   if [[ -n "$selected_folder" ]]; then
-    echo "Opening $selected_folder notes with $EDITOR"
+    printf "Opening %s notes with %s\n" "$selected_folder" "$EDITOR"
     cd "$selected_folder" || {
-      echo "[ERROR] Failed to change directory to $selected_folder"
+      printf "[ERROR] Failed to change directory to %s\n" "$selected_folder" >&2
       exit 1
     }
 
   else
-    echo "No folder selected, opening $target_directory with $EDITOR"
+    printf "No folder selected, opening %s with %s\n" "$target_directory" "$EDITOR"
   fi
 fi
 
@@ -79,6 +79,6 @@ fi
 $EDITOR .
 
 cd ~ || {
-  echo "[ERROR] Failed to change directory to home"
+  printf "[ERROR] Failed to change directory to home\n" >&2
   exit 1
 }
diff --git a/.local/bin/screenshot b/.local/bin/screenshot
--- a/.local/bin/screenshot
+++ b/.local/bin/screenshot
@@ -3,6 +3,9 @@
 # ┌────────────┐
 # │ screenshot │
 # └────────────┘
+# Take screenshots with `grim` and `slurp`.
+# Flags:
+# `-c` or `cut` screenshots a selected region.
 
 save_dir="$HOME/Pictures/Screenshots"
 timestamp=$(date +%F_%H-%M-%S)
@@ -10,7 +13,7 @@ new_save="$save_dir/screenshot-$timestamp.png"
 
 # Create Screenshot dir if it doesn't exist
 if [[ ! -d "$save_dir" ]]; then
-  echo "Creating $save_dir as screenshots directory"
+  printf "Creating %s as screenshots directory\n" "$save_dir"
   mkdir -p "$save_dir"
 fi
 
@@ -19,7 +22,7 @@ if [[ "$1" == "cut" || "$1" == "-c" ]]; then
   region=$(slurp)
 
   if [[ -z "$region" ]]; then
-    echo "Region selection canceled. Exiting..."
+    printf "Region selection canceled. Exiting...\n"
     exit 0
   fi
 
@@ -28,28 +31,28 @@ else
 
   # Full-screen screenshot
   for i in {4..1}; do
-    echo -ne "\rTaking fullscreen screenshot in $i seconds..."
+    printf "\rTaking fullscreen screenshot in %d seconds..." "$i"
     sleep 1
   done
-  echo ""
+  printf "\n"
 
   grim "$new_save"
 fi
 
 # Check if the screenshot was created
 if [[ ! -f "$new_save" ]]; then
-  echo "[ERROR] Screenshot was not saved. Exiting..."
+  printf "[ERROR] Screenshot was not saved. Exiting...\n" >&2
   exit 1
 fi
 
 # Prompt for new filename after taking the screenshot
-echo -ne "Rename screenshot or press 'Enter' to keep default: "
+printf "Rename screenshot or press 'Enter' to keep default: "
 read -r screenshot_name
 
 if [[ -n "$screenshot_name" ]]; then
   save_as="$save_dir/$screenshot_name.png"
   mv "$new_save" "$save_as"
-  echo "Screenshot saved as $save_as"
+  printf "Screenshot saved as %s\n" "$save_as"
 else
-  echo "Screenshot saved as $new_save"
+  printf "Screenshot saved as %s\n" "$new_save"
 fi
diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -1,6 +1,9 @@
 #!/bin/bash
 # dotfiles - Main entry script
 
+RED=$(tput setaf 1)
+NC=$(tput sgr0)
+
 get_dotfiles_path() {
   if [ ! -L "$0" ]; then
     # If path is no symlink
@@ -19,7 +22,7 @@ check_dependencies() {
 
   for dep in "${dependencies[@]}"; do
     if ! command -v "$dep" >/dev/null; then
-      echo "[ERROR]: $dep is required. Please install $dep to continue."
+      printf "%sERROR%s '%s' is required. Please install '%s' to continue.\n" "${RED}" "${NC}" "$dep" "$dep" >&2
       exit 1
     fi
   done
@@ -40,13 +43,13 @@ execute() {
   # ┌───────────────────────┐
   # │ 4lexandrei's Dotfiles │
   # └───────────────────────┘
-  echo -ne "┌───────────────────────┐\n│ 4lexandrei's Dotfiles │\n└───────────────────────┘\n"
+  printf "┌───────────────────────┐\n│ 4lexandrei's Dotfiles │\n└───────────────────────┘\n"
 
   if [ -n "$selected_script" ]; then
-    echo ":: Running $(basename "$selected_script")..."
+    printf ":: Running %s...\n" "$(basename "$selected_script")"
     "$selected_script"
   else
-    echo "No script selected."
+    printf "No script selected\n"
   fi
 }
 
